### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by BBruington**
Cleaned up the code and improved readability.

### CODE REVIEW

**Comment by BBruington** [comment]
My only question which was brought up with Amanda is whether we should abstract the formatEnumString function to somewhere besides actions.ts.

**Review by Balance8 — COMMENTED** [review]
If we are going to do a clean up then we should use zod: https://www.youtube.com/watch?v=h3w9tQoXx5Ic

**Review by Balance8 — COMMENTED** [review]
Also add Optimistic UI https://www.youtube.com/watch?v=Pz8CAbeg6Q0

**Review by Balance8 — COMMENTED** [review]
```
import { z } from 'zod';

// Schemas
const RemovePhotoSchema = z.object({
  photoId: z.string(),
});

const UpdateDisplayNameSchema = z.object({
  newName: z.string().min(1, "Name cannot be empty"),
  userId: z.string(),
});

const HandlePhotoShootTypeSchema = z.object({
  action: z.enum(['connect', 'disconnect']), 
  photoShootTypeName: z.string(),
  userId: z.string(),
});

const HandlePhotographySkillSchema = z.object({
  action: z.enum(['connect', 'disconnect']),
  photographySkill: z.object({
    name: z.string(),
    skillType: z.string(),
  }),
  userId: z.string(),
});
```

```
export const removePhoto = async (props: unknown) => {
  const { photoId } = RemovePhotoSchema.parse(props);
  // The rest of the function remains the same
}

export const updateDisplayName = async (props: unknown) => {
  const { newName, userId } = UpdateDisplayNameSchema.parse(props);
  // The rest of the function remains the same
}

export const handleConnectPhotoShootType = async (props: unknown) => {
  const { action, photoShootTypeName, userId } = HandlePhotoShootTypeSchema.parse(props);
  // The rest of the function remains the same
}

export const handleConnectPhotographySkill = async (props: unknown) => {
  const { action, photographySkill, userId } = HandlePhotographySkillSchema.parse(props);
  // The rest of the function remains the same
}
```

**Review by Balance8 — APPROVED** [review]

**Pull request merged**
