### PR TITLE
Add Tailwind CSS configuration and update welcome message

### PR DESCRIPTION
**Pull request by Balance8**

### CODE REVIEW

**Comment by amanda-post** [comment]
Please add the prettier tailwind plugin uwu

**Comment by Balance8** [comment]
> Please add the prettier tailwind plugin uwu

Will do

**Comment by hhhssh** [comment]
Can you add a screenshot please?

**Comment by BBruington** [comment]
Looks good to me!

**Comment by Balance8** [comment]
> Can you add a screenshot please?

image

**Review by amanda-post — APPROVED** [review]

**Comment by BBruington** [comment]
Glad to have the tailwind prettier plugin.

**Review by BBruington — APPROVED** [review]
Very good

**Comment by hhhssh** [comment]
lgtm! When/if we have to add in more plugins for different libraries do we have to send a pull request for it or can we add it on our own?

**Pull request merged**
