### PR TITLE
No ticket/remove excess schema and add colors

### PR DESCRIPTION
**Pull request by amanda-post**
reopen PR

### CODE REVIEW

**Review by DinDin985 — APPROVED** [review]
Lgtm! 👍

**Comment by Balance8** [comment]
Lets change to a svg later, thanks

**Comment by BBruington** [comment]
I like it!

**Review by Balance8 — DISMISSED** [review]

**Review by BBruington — APPROVED** [review]
Good job

**Comment by Balance8** [comment]
I merged the schema in and tested auth and one of the changes is breaking next-auth.  Will need to refine before we merge.  Also we need to add a planetscale automation to catch this in the pr and automate the merging schema into main.

**Pull request closed without merging**
